const Razorpay = require('razorpay');
const crypto = require('crypto');

const razor = new Razorpay({
  key_id: process.env.RAZORPAY_KEY_ID,
  key_secret: process.env.RAZORPAY_KEY_SECRET
});


exports.createOrder = async (req, res) => {

  const { bookingId, amount } = req.body;

  try {
    const order = await razor.orders.create({
      amount: Math.round(amount * 100),
      currency: "INR",
      receipt: `booking_${bookingId}`,
      payment_capture: 1
    });
    res.json(order);
  }
  catch (err) {
    console.error("❌ Razorpay Error:", err);   // full error object
    res.status(500).json({ error: err.message });
  }
};

exports.verifyPayment = async (req, res) => {
  const { razorpay_order_id, razorpay_payment_id, razorpay_signature, bookingId } = req.body;

  const hmac = crypto.createHmac('sha256', process.env.RAZORPAY_KEY_SECRET);
  hmac.update(razorpay_order_id + '|' + razorpay_payment_id);
  const generate_signature = hmac.digest('hex');

  console.log("✍️ Signature from Client:", razorpay_signature);
  console.log("✍️ Signature Generated by Backend:", generate_signature);

  if (generate_signature === razorpay_signature) {
    // Payment verified successfully, update booking status and payment status
    try {
      const Booking = require('../models/Booking');
      const { sendBookingConfirmation } = require('../utils/emailService');

      const booking = await Booking.findByIdAndUpdate(
        bookingId,
        { status: 'booked', paymentStatus: 'paid' },
        { new: true }
      ).populate('partner').populate('user');

      if (!booking) {
        return res.status(404).json({ error: 'Booking not found' });
      }

      console.log("✅ Payment verified and booking status updated to 'booked' with payment 'paid'");

      // Send booking confirmation email in the background
      if (booking.user && booking.user.email) {
        sendBookingConfirmation(booking.user.email, booking.user.name, {
          bookingId: booking._id,
          partnerName: booking.partner.name,
          partnerCity: booking.partner.address?.city || 'N/A',
          startDate: booking.startAt,
          endDate: booking.endAt,
          weightKg: booking.weightKg,
          totalAmount: booking.price,
          status: booking.status,
          paymentStatus: booking.paymentStatus
        })
          .then(() => console.log("✅ Booking confirmation email sent"))
          .catch(emailError => console.error('Email sending failed:', emailError.message));
      }

      return res.json({ ok: true, bookingId: booking._id });
    } catch (err) {
      console.error("❌ Error updating booking status:", err);
      return res.status(500).json({ error: 'Payment verified but failed to update booking' });
    }
  }
  res.status(400).json({ error: "invalid Signature" });
};